#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     IRSEEKER,       sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motor_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor_right,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorFly,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servoBucket,          tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoBlock,           tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoFlagAdjust,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Robotics and Programming Guild Code

#define SLOW_MOVEMENT 30
#define liftPower 25
//#define motor_right 	1
//#define motor_left 		2
#include "JoystickDriver.c" //brings in controller functions

//#include "function_library.c"

int threshold = 10; //determines whether non-zero variables in joystick position are hardware error or human intervention
bool motorRun; //determines if the motors are running
bool flagMove = false;
bool liftRun = false;

void forward(int power){  //makes the robot move forward
	motor[motor_right] = power * 0.75;
	motor[motor_left] = power * 0.75;

	motorRun = true; //tells it the motor is running
}

void turn(int power){ //move to the right on positive power
	motor[motor_right] = -power * 0.75;
	motor[motor_left] = power * 0.75;
	motorRun = true; //tells it the motor is running
}

void stopMotion(){ //terminates movement if no control is enacted
	motor[motor_right] = 0;
	motor[motor_left] = 0;
}

void stopLiftMotion()
{
	motor[motorLift] = 0;
	motor[motorFlag] = 0;
}

void initializeRobot(){  //ethan is a nerd. Also, this is what you run to save power when the robot starts by disabling unnecessary systems
//	disableDiagnosticDisplay();
	bFloatDuringInactiveMotorPWM = false;
	return;
}

task main(){
	bool liftMotorRun;
	initializeRobot();
	//waitForStart();
	getJoystickSettings(joystick);

	while( true ) { //infinite loop for control
		motorRun = false;

		if( abs(joystick.joy1_y1) > threshold ){ //right joystick control. When the left joystick is pushed forward, move forward
			float fPower = (joystick.joy1_y1 * 100 / 128);
			int iPower = fPower;
			forward(iPower);
		}
		if( abs(joystick.joy1_x2) > threshold ){ //if right joystick is pulled left or right, turn to go in the same direction.
			float fPower = (-joystick.joy1_x2 * 100 / 128);
			int iPower = fPower;
			turn(iPower);
	  }

		bool liftTooLow = false;
		if(SensorValue(touch) == 1){
			liftTooLow = true;
		}

		if (joy2Btn(1) == 1)
		{
			servo[motorLift] = (ServoValue[motorLift] + 1);
		}

		if(joy2Btn(3) == 1)
		{
			servo[motorLift] = (ServoValue[motorLift] - 1);
		}

		if(joy2Btn(2) == 1)
		{
			motor[motorLift] = liftPower;
			liftMotorRun = false;
		}

		if(joy2Btn(4) == 1 && liftTooLow == false)
		{
			motor[motorLift] = -liftPower;
			liftMotorRun = false;
		}

		if(joy2Btn(2) == 1)
		{
			servo[servoBucket] += 1;
		}

		if(joy2Btn(5) == 1)
		{
			servo[servoFlagAdjust] = 127;
		}
		else if(joy2Btn(7) == 1)
		{
			servo[servoFlagAdjust] = -127;
		}
		else {
			servo[servoFlagAdjust] = 0;
		}

		if(joy2Btn(4) == 1)
		{
			servo[servoBucket] -= 1;
		}

		if(joy1Btn(6) == 1)
		{
			motor[motorFlag] = 50;
		}

		if( motorRun == false ){ //stops the motors from running if nothing is pressed. Must be updated to account for all motor functions added to the program.
			stopMotion();
		}

		if( liftMotorRun == false ){
		 	stopLiftMotion();
		}

		if( abs(joystick.joy2_y1) > threshold ){
			motor[motorLift] = (joystick.joy2_y1 * 100) / 128;
			liftRun = true;
		}

		if(liftRun == false){
			stopLiftMotion();
		}

	}

	//if the touch sensor goes off, so does the motor.


}
