#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     IRSEEKER,       sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motor_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor_right,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorFly,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servoBucket,          tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoBlock,           tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoFlagAdjust,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Robotics and Programming Guild Code

#define SLOW_MOVEMENT 30
//#define motor_right 	1
//#define motor_left 		2
#include "JoystickDriver.c" //brings in controller functions

//#include "function_library.c"

int threshold = 10; //determines whether non-zero variables in joystick position are hardware error or human intervention
bool motorRun; //determines if the motors are running

void forward(int power){  //makes the robot move forward
	motor[right_front] = power * 0.75;
	motor[left_front] = power * 0.75;
//	motor[right_back] = power * 0.75;
//	motor[left_back] = power * 0.75;
	motorRun = true; //tells it the motor is running
}

void turn(int power){ //move to the right on positive power
	motor[right_front] = power * 0.75;
	motor[left_front] = -power * 0.75;
//	motor[right_back] = power * 0.75;
//	motor[left_back] = -power * 0.75;
	motorRun = true; //tells it the motor is running
}

void stopMotion(){ //terminates movement if no control is enacted
	motor[right_front] = 0;
	motor[left_front] = 0;
//	motor[right_back] = 0;
//	motor[left_back] = 0;
}

void initializeRobot(){  //ethan is a nerd. Also, this is what you run to save power when the robot starts by disabling unnecessary systems
//	disableDiagnosticDisplay();
	bFloatDuringInactiveMotorPWM = false;
	return;
}

task main(){
	initializeRobot();
	//waitForStart();
	getJoystickSettings(joystick);

	while( true ) { //infinite loop for control
		motorRun = false;

		if( abs(joystick.joy1_y1) > threshold ){ //right joystick control. When the left joystick is pushed forward, move forward
			float fPower = (joystick.joy1_y1 * 100 / 128);
			int iPower = fPower;
			forward(iPower);
		}
		if( abs(joystick.joy1_x1) > threshold ){ //if right joystick is pulled left or right, turn to go in the same direction.
			float fPower = (joystick.joy1_x1 * 100 / 128);
			int iPower = fPower;
			turn(iPower);
	  }

	  if( joy1Btn(5) == 1 ){
	  	servo[craneBottom1] = (ServoValue[craneBottom1] + 1);
	  } //if joystick button LB is pressed, CraneBottom servo value will increase by one with each click

	  if( joy1Btn(6) == 1){
	  	servo[craneBottom2] = (ServoValue[craneBottom2] + 1);
	  } //if joystick button RB is pressed, CraneTop servo value will increase by one with each click

	  if(joy1Btn(7) == 1){
	  	servo[craneBottom1] = (ServoValue[craneBottom1] - 1);
	  } //if joystick button LT is pressed, CraneBotton servo value will decrease by one with each click

	  if(joy1Btn(8) == 1){
	  	servo[craneBottom2] = (ServoValue[craneBottom2] - 1);
	  } //if joystick button RT is pressed, CraneTop servo value will decrease by one with each click


		if( motorRun == false ){ //stops the motors from running if nothing is pressed. Must be updated to account for all motor functions added to the program.
			stopMotion();
		}
	}
}
