#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     IRSEEKER,       sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motor_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor_right,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorFly,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servoBucket,          tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoBlock,           tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoFlagAdjust,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Robotics and Programming Guild Code
#include "function_library.c"
#include "JoystickDriver.c" //brings in controller functions

#define SERVO_START_POINT				230
#define SERVO_DELIVER_POINT		 70
#define IR_SENSOR_POINT						4
task main()
{
	servo[autoBlock] = SERVO_START_POINT;

	waitForStart(); // Wait for the beginning of driver phase.

	while(HTIRS2readACDir(IR) != IR_SENSOR_POINT) { //checks location of IR and moves forward if not at the IR basket
		forward(40);
	}
	stops();
	if(HTIRS2readACDir(IR) == IR_SENSOR_POINT){
			servo[autoBlock] = SERVO_DELIVER_POINT;
			wait1Msec(250);
			servo[autoBlock] = SERVO_START_POINT;
	}
	moveDist(100, 100, 40);
	dropAutoBucket(200);
	//raises bucket arm to deposit block into the bucket
}
