#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     IRSEEKER,       sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motor_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor_right,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorFly,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servoBucket,          tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoBlock,           tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoFlagAdjust,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Robotics and Programming Guild Code
//#include "function_library.c"
#include "JoystickDriver.c" //brings in controller functions

/* =====================================================
	 = Program constant definitions
	 ===================================================== */
/*#define SLOW_MOVEMENT 	30
#define SLOW_MOVEMENT_TURN   50*/
#define SLOW_POWER 	30		// If Button 5 Pressed drive at 30% of current
#define MID_POWER		60		// If Button 7 Pressed drive at 60% of current
#define POWER				100

#define LIFT_POWER 			90
#define FLAG_POWER 			75
#define BEGINNING_POINT 90
#define JOY_THRESHOLD		10

/* =====================================================
	 = Program global variables
	 ===================================================== */
bool flagMotorRun = false;	// determines if the flag motors are running
// this has not been implemented yet // bool liftTooLow = false;    // determines if the lift is too low and will run against the ground
bool bucketMoving = false;
/* =====================================================
	 = Drive motor functions
	 ===================================================== */
/*void forward(int power){  //makes the robot move forward
	motor[motor_right] = power * 0.75;
	*/



/* =====================================================
	 = Activators functions
	 ===================================================== */
void stopLiftMotor() {
	motor[motorLift] = 0;
}

void stopFlagMotor() {
	motor[motorFlag] = 0;
}

/*task doBucketThing(){ //this will not be used. We'll just keep it around in case we decide to use it later on.
	servo[bucket] = BEGINNING_POINT - 40;
	wait1Msec(100);
	servo[bucket] = BEGINNING_POINT;
}*/

/* =====================================================
	 = General FTC/Robot functions
	 ===================================================== */
void initializeRobot(){
	//bDisplayDiagnostics = false;
	bFloatDuringInactiveMotorPWM = false;
	return;
}

task main() {
	initializeRobot();

	while( true ) { //infinite loop for control
		flagMotorRun = false;
		bucketMoving = false;
/*		if(SensorValue[touch1] == 1){
			liftTooLow = true;
		}

		*/

		getJoystickSettings(joystick);

		/* =====================================================
			 = Run Controller 1 - Drive Motors
			 ===================================================== */
		if(abs(joystick.joy1_y1) > JOY_THRESHOLD) {
			int nowPower = POWER;
			if(joy1Btn(5)){
				nowPower = MID_POWER;
			}
			if(joy1Btn(7)){
				nowPower = SLOW_POWER;
			}
			nowPower = ((joystick.joy1_y1 * nowPower) /128);
			motor[motor_left] = nowPower;
		}
		else {
			motor[motor_left] = 0;
		}

		if(abs(joystick.joy1_y2) > JOY_THRESHOLD) {
			int nowPower = POWER;
			if(joy1Btn(5)){
				nowPower = MID_POWER;
			}
			if(joy1Btn(7)){
				nowPower = SLOW_POWER;
			}
			nowPower = ((joystick.joy1_y2 * nowPower) /128);
			motor[motor_right] = nowPower;
		}
		else {
			motor[motor_right] = 0;
		}
		/* =====================================================
			 = Run Controller 2 - Activators
			 ===================================================== */
		// Raise and Lower the Lift
		if(abs(joystick.joy1_y1) > JOY_THRESHOLD && joystick.joy1_y1 > 0) {
			motor[motorLift] = (joystick.joy2_y1 * 128 / 100);
//			liftMotorRun = true;
		}
		else{
			motor[motorLift] = 0;
		}

		// Run the flag motor forward or backward
		if(joy2Btn(6) == 1) {
			motor[motorFlag] = -FLAG_POWER;
			flagMotorRun = true;
		}
		if(joy2Btn(8) == 1) {
			motor[motorFlag] = (FLAG_POWER);
			flagMotorRun = true;
		}

		if(joy2Btn(2) == 1 && joy2Btn(4) == 1){
			servo[servoBucket] = BEGINNING_POINT + 20;
			bucketMoving = true;
		}

		// Tilt the bucket backward and forward
		if(joy2Btn(2) == 1 && bucketMoving == false) {
			servo[servoBucket] += 1;
		}
		if(joy2Btn(4) == 1 && bucketMoving == false) {
			servo[servoBucket] -= 1;
		}

		if(joy2Btn(1) == 1){
			servo[servoBucket] = BEGINNING_POINT - 40;
		}

		// Reset bucket into correct position
		if(joy2Btn(3) == 1){
			servo[servoBucket] = BEGINNING_POINT + 70;
		}

		if(joy2Btn(5) == 1)
		{
			servo[servoFlagAdjust] += 1;
		}

		if(joy2Btn(7) == 1)
		{
			servo[servoFlagAdjust] -= 1;
		}

		/* =====================================================
			 = Stop mottors that are not running
			 ===================================================== */
		if( flagMotorRun == false ) {
			stopFlagMotor();
		}
	}
}
