#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     IRSEEKER,       sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motor_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor_right,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorFly,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servoBucket,          tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servoBlock,           tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servoFlagAdjust,      tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Robotics and Programming Guild Code
//#include "function_library.c"
#include "JoystickDriver.c" //brings in controller functions

/* =====================================================
	 = Program constant definitions
	 ===================================================== */
#define SLOW_MOVEMENT 	30
#define SLOW_MOVEMENT_TURN   50
#define LIFT_POWER 			90
#define FLAG_POWER 			75
#define BEGINNING_POINT 90
#define JOY_THRESHOLD		10

/* =====================================================
	 = Program global variables
	 ===================================================== */
bool motorRun = false; 			// determines if the drive motors are running
bool liftMotorRun = false;	// determines if the lift motors are running
bool flagMotorRun = false;	// determines if the flag motors are running
bool liftTooLow = false;    // determines if the lift is too low and will run against the ground
bool bucketMoving = false;

/* =====================================================
	 = Drive motor functions
	 ===================================================== */
void forward(int power){  //makes the robot move forward
	motor[motor_right] = power * 0.75;
	motor[motor_left] = power * 0.75;
	motorRun = true; //tells it the motor is running
}

void turn(int power){ //move to the right on positive power
	motor[motor_right] = -power; // * 0.75;
	motor[motor_left] = power; // * 0.75;
	motorRun = true; //tells it the motor is running
}

void stopMotion(){ //terminates movement if no control is enacted
	motor[motor_right] = 0;
	motor[motor_left] = 0;
}

/* =====================================================
	 = Activators functions
	 ===================================================== */
void stopLiftMotor() {
	motor[motorLift] = 0;
}

void stopFlagMotor() {
	motor[motorFlag] = 0;
}

task doBucketThing(){ //this will not be used. We'll just keep it around in case we decide to use it later on.
	servo[bucket] = BEGINNING_POINT - 40;
	wait1Msec(100);
	servo[bucket] = BEGINNING_POINT;
}

/* =====================================================
	 = General FTC/Robot functions
	 ===================================================== */
void initializeRobot(){
	bDisplayDiagnostics = false;
	bFloatDuringInactiveMotorPWM = false;
	return;
}

task main() {
	initializeRobot();
	if(SensorValue[touch1] == 1){
		liftTooLow = true;
	}

	while( true ) { //infinite loop for control
		motorRun = false;
		liftMotorRun = false;
		flagMotorRun = false;
		bucketMoving = false;

		getJoystickSettings(joystick);

		/* =====================================================
			 = Run Controller 1 - Drive Motors
			 ===================================================== */
		// Move the robot forwards and backwards
		if( abs(joystick.joy1_y1) > JOY_THRESHOLD ){
			float fPower = (joystick.joy1_y1 * 100 / 128);
			int iPower = fPower;
			forward(-iPower);
		}
		// Turn the robot left or right
		if( abs(joystick.joy1_x2) > JOY_THRESHOLD ){
			float fPower = (-joystick.joy1_x2 * 100 / 128);
			int iPower = fPower;
			turn(iPower);
	  }

	  if( joystick.joy1_TopHat == 4 ){ //moves forward slowly when D-pad is pressed up
	  	forward(SLOW_MOVEMENT);
	  }
	  if(joystick.joy1_TopHat == 0 ){ //d-pad down, move back slow
	  	forward(-SLOW_MOVEMENT);
	  }

	  if(joystick.joy1_TopHat == 2) { //turns right slowly if the rightmost D-pad is pressed
	  	turn(-SLOW_MOVEMENT_TURN);
	  }
	  if(joystick.joy1_TopHat == 6) { //turns left slowly if the leftmost D-pad is pressed
	 		turn(SLOW_MOVEMENT_TURN);
	 	}

		/* =====================================================
			 = Run Controller 2 - Activators
			 ===================================================== */
		// Raise and Lower the Lift
		if(joy2Btn(5) == 1) {
			motor[motorLift] = LIFT_POWER;
			liftMotorRun = true;
		}
		if(joy2Btn(7) == 1 && liftTooLow == false) {
			motor[motorLift] = -LIFT_POWER;
			liftMotorRun = true;
		}

		// Run the flag motor forward or backward
		if(joy2Btn(6) == 1) {
			motor[motorFlag] = -FLAG_POWER;
			flagMotorRun = true;
		}
		if(joy2Btn(8) == 1) {
			motor[motorFlag] = (FLAG_POWER);
			flagMotorRun = true;
		}

		if(joy2Btn(2) == 1 && joy2Btn(4) == 1){
			servo[bucket] = BEGINNING_POINT + 20;
			bucketMoving = true;
		}

		// Tilt the bucket backward and forward
		if(joy2Btn(2) == 1 && bucketMoving == false) {
			servo[bucket] += 1;
		}
		if(joy2Btn(4) == 1 && bucketMoving == false) {
			servo[bucket] -= 1;
		}

		if(joy2Btn(1) == 1){
			servo[bucket] = BEGINNING_POINT - 40;
		}

		// Reset bucket into correct position
		if(joy2Btn(3) == 1){
			servo[bucket] = BEGINNING_POINT + 70;
		}

		/* =====================================================
			 = Stop mottors that are not running
			 ===================================================== */
		if( motorRun == false ) {
			stopMotion();
		}
		if( liftMotorRun == false ) {
		 	stopLiftMotor();
		}
		if( flagMotorRun == false ) {
			stopFlagMotor();
		}
	}
}
